(* Text display of a the commands in the commands catalog *)

let text_display = [
	("FEMTO", "\001");
	("PICO", "\002");
	("NANO", "\003");
	("MICRO", "\004");
	("MILLI", "\005");
	("KILO", "\006");
	("MEGA", "\007");
	("GIGA", "\008");
	("TERA", "\009");
	("PETA", "\010");
	("EXA", "\011");
	("DISP", "\012");
	("EOL", "\013");
	("ASSIGN", "\014");
	("TIMESTENPOWER", "\015");
	("LEQ", "\016");
	("DIFFERENT", "\017");
	("GEQ", "\018");
	("IMPL", "\019");
	("FONE", "f1");
  ("FTWO", "f2");
  ("FTHREE", "f3");
  ("FFOUR", "f4");
  ("FFIVE", "f5");
  ("FSIX", "f6");
	("QUOTE", "\034");
	("LPAR", "(");
	("RPAR", ")");
	("COLON", ":");
	("LESS", "<");
	("EQUAL", "=");
	("GREATER", ">");
	("QMARK", "?");
	("LSQBRACKET", "[");
	("RSQBRACKET", "]");
	("LBRACKET", "{");
	("RBRACKET", "}");
	("POLPAR", "Pol(");
	("SIN", "sin ");
	("COS", "cos ");
	("TAN", "tan ");
  ("SMALLH", "h");
	("LN", "ln ");
	("SQRT", "\134");
	("UMINUS", "\135");
	("THICKP", "\136");
	("PLUS", "+");
  ("LOWERCASEXNOR", "xnor");
	("POWER2", "\139");
	("COORDSIGN", "\140");
	("INTEGRALPAR", "\230\187(");
	("MMOD", "Mod");
  ("SIGMAXSQUARE", "\229\081x\229\194");
	("ARCSIN", "sin\155 ");
	("ARCCOS", "cos\155 ");
	("ARCTAN", "tan\155 ");
  ("SMALLD", "d");
	("LOG", "log ");
	("CURT", "\229\223\134");
	("ABS", "Abs ");
	("THICKC", "\152");
	("MINUS", "\153");
  ("LOWERCASEXOR", "xor");
	("POWERMINUS1", "\155");
	("DEGREESIGN", "\156");
	("MED", "Med");
  ("SIGMAX", "\229\081x");
	("RECPAR", "Rec(");
	("SINH", "sinh ");
	("COSH", "cosh ");
	("TANH", "tanh ");
  ("SMALLO", "o");
	("EPOWER", "e\168");
	("INT", "Int ");
  ("HIDDENNOT", "Not ");
	("POWER", "\168");
	("TIMES", "\169");
  ("LOWERCASEOR", "or");
	("EXCLAMATIONMARK", "\171");
	("RADIANSIGN", "\172");
	("MINY", "minY");
  ("MINX", "minX");
  ("NSTAT", "n");
	("ARCSINH", "sinh\155 ");
	("ARCCOSH", "cosh\155 ");
	("ARCTANH", "tanh\155 ");
  ("SMALLB", "b");
	("TENPOWER", "\181");
	("FRAC", "Frac ");
  ("NEG", "Neg ");
	("NSQRT", "\229\221\134");
	("DIVIDED", "\185");
  ("LOWERCASEAND", "and");
	("FRACSIGN", "\187");
	("GRADSIGN", "\188");
	("MAXY", "maxY");
  ("MAXX", "maxX");
  ("SIGMAYSQUARE", "\229\081y\229\194");
	("ANS", "Ans");
	("RAN", "Ran\035 ");
	("XBAR", "\194");
  ("SMALLSIGMAX", "\230\081x");
  ("YBAR", "\195");
  ("SX", "sx");
  ("SMALLSIGMAY", "\230\081y");
  ("SY", "sy");
  ("AREG","a");
  ("BREG", "b");
  ("RREG", "r");
  ("XHAT", "\203");
  ("YHAT", "\204");
	("SMALLR", "\205");
	("THETA", "\206");
	("SIGMAY", "\229\081y");
	("PI", "\208");
	("CLS", "Cls");
	("RND", "Rnd");
  ("DEC", "Dec");
  ("HEX", "Hex");
  ("BIN", "Bin");
  ("OCT", "Oct");
  ("WHITERECT", "\216");
	("NORM", "Norm ");
	("DEG", "Deg");
	("RAD", "Rad");
	("GRA", "Gra");
	("ENG", "Eng");
	("INTG", "Intg ");
	("SIGMAXY", "\229\081xy");
	("PLOT", "Plot ");
	("LINE", "Line");
	("LBL", "Lbl ");
	("FIX", "Fix ");
	("SCI", "Sci ");
	("DSZ", "Dsz ");
	("ISZ", "Isz ");
	("FACTOR", "Factor ");
	("VIEWWINDOW", "ViewWindow ");
	("GOTO", "Goto ");
	("PROG", "Prog ");
	("GRAPHYEQ", "Graph Y=");
	("GRAPHS", "Graph \230\187");
	("GRAPHYG", "Graph Y>");
	("GRAPHYL", "Graph Y<");
	("GRAPHYGEQ", "Graph Y\018");
	("GRAPHYLEQ", "Graph Y\016");
	("GRAPHREQ", "Graph r=");
	("GRAPHXYEQ", "Graph(X,Y)=(");
  ("HIDDENCOMMA", ",");
	("PPAR", "P(");
	("QPAR", "Q(");
	("RPAR", "R(");
	("TPAR", "t(");
	("XMIN", "Xmin");
  ("XMAX", "Xmax");
  ("XSCL", "Xscl");
  ("YMIN", "Ymin");
  ("YMAX", "Ymax");
  ("YSCL", "Yscl");
  ("TTHETAMIN", "T\230\071min");
  ("TTHETAMAX", "T\230\071max");
  ("TTHETAPTCH", "T\230\071ptch");
  ("XFCT", "Xfct");
  ("YFCT", "Yfct");
  ("DSTART", "D Start");
  ("DEND", "D End");
  ("DPITCH", "D pitch");
  ("RIGHTXMIN", "RightXmin");
  ("RIGHTXMAX", "RightXmax");
  ("RIGHTXSCL", "RightXscl");
  ("RIGHTYMIN", "RightYmin");
  ("RIGHTYMAX", "RightYmax");
  ("RIGHTYSCL", "RightYscl");
  ("RIGHTTTHETAMIN", "RightT\230\071min");
  ("RIGHTTTHETAMAX", "RightT\230\071max");
  ("RIGHTTTHETAPTCH", "RightT\230\071ptch");
  ("CREG", "c");
  ("DREG", "d");
  ("EREG", "e");
	("MAX", "Max(");
	("DET", "Det ");
	("ARG", "Arg ");
	("CONJG", "Conjg ");
	("REP", "ReP ");
	("IMP", "ImP ");
	("DOVERDX", "d/dx(");
	("DSQOVERDXSQ", "d\139/dx\139");
	("SOLVE", "Solve(");
	("SIGMAPAR", "\229\081(");
	("FMIN", "FMin(");
	("FMAX", "FMax(");
	("SEQ", "Seq(");
	("MIN", "Min(");
	("MEAN", "Mean(");
	("MEDIAN", "Median(");
	("SOLVEN", "SolveN(");
	("MOD", "MOD(");
	("MODEXP", "MOD_Exp(");
	("GCD", "GCD(");
	("LCM", "LCM(");
	("STDDEV", "StdDev(");
  ("VARIANCE", "Variance(");
	("MAT", "Mat ");
	("TRN", "Trn ");
	("STARROW", "\042Row ");
	("STARROWPLUS", "\042Row+ ");
	("ROWPLUS", "Row+ ");
	("SWAP", "Swap ");
	("DIM", "Dim ");
	("FILL", "Fill(");
	("IDENTITY", "Identity ");
	("AUGMENT", "Augment(");
	("LISTTOMAT", "List\014Mat(");
	("MATTOLIST", "Mat\014List(");
	("SUM", "Sum ");
	("PROD", "Prod ");
	("PERCENT", "Percent ");
	("CUML", "Cuml ");
	("CPLXI", "\127\080");
	("LIST", "List ");
	("DELTALIST", "\229\067List ");
	("CHEVRON", "\127\084");
	("REF", "Ref ");
	("RREF", "Rref ");
	("BLACKARROW", "\230\158");
	("SIMCOEF", "Sim Coef");
  ("PLYCOEF", "Ply Coef");
  ("SIMRESULT", "Sim Result");
  ("PLYRESULT", "Ply Result");
  ("NTVM", "n");
  ("IPERCENT", "I\037");
  ("PV", "PV");
  ("PMT", "PMT");
  ("FV", "FV");
  ("LISTONE", "List1");
  ("LISTTWO", "List2");
  ("LISTTHREE", "List3");
  ("LISTFOUR", "List4");
  ("LISTFIVE", "List5");
  ("LISTSIX", "List6");
  ("QONE", "Q\229\209");
  ("QTHREE", "Q\229\211");
  ("XONE", "x\229\209");
  ("YONE", "y\229\209");
  ("XTWO", "x\229\210");
  ("YTWO", "y\229\210");
  ("XTHREE", "x\229\211");
  ("YTHREE", "y\229\211");
	("LOGAB", "logab(");
	("RNDFIX", "RndFix(");
	("RANINT", "RanInt\035(");
	("RANLIST", "RanList\035(");
	("RANBIN", "RanBin\035(");
	("RANNORM", "RanNorm\035(");
	("SIGMAAN", "\230\081a\229\222");
  ("SIGMABN", "\230\081b\229\222");
  ("SIGMACN", "\230\081c\229\222");
	("GETKEY", "Getkey");
	("FRESULT", "F Result");
  ("FSTART", "F Start");
  ("FEND", "F End");
  ("FPITCH", "F pitch");
  ("RRESULT", "R Result");
  ("RSTART", "R Start");
  ("REND", "R End");
  ("HSTART", "H Start");
  ("HPITCH", "H pitch");
	("TOSIMP", "\230\158Simp ");
	("AN", "a\229\222");
  ("ANPLUSONE", "a\229\222\229\219\229\206");
  ("ANPLUSTWO", "a\229\222\229\219\229\207");
  ("NRECUR", "\229\222");
  ("AZERO", "a\229\205");
  ("AONE", "a\229\206");
  ("ATWO", "a\229\207");
  ("BN", "b\229\222");
  ("BNPLUSONE", "b\229\222\229\219\229\206");
  ("BNPLUSTWO", "b\229\222\229\219\229\207");
  ("BZERO", "b\229\205");
  ("BONE", "b\229\206");
  ("BTWO", "b\229\207");
  ("ANSTART", "a\229\222Start");
  ("BNSTART", "b\229\222Start");
	("AND", " And ");
	("OR", " Or ");
	("NOT", "Not ");
	("XOR", " Xor ");
	("SIGMAANPLUSONE", "\230\081a\229\222\229\219\229\206");
  ("SIGMABNPLUSONE", "\230\081b\229\222\229\219\229\206");
  ("SIGMACNPLUSONE", "\230\081c\229\222\229\219\229\206");
  ("SIGMAANPLUSTWO", "\230\081a\229\222\229\219\229\207");
  ("SIGMABNPLUSTWO", "\230\081b\229\222\229\219\229\207");
  ("SIGMACNPLUSTWO", "\230\081c\229\222\229\219\229\207");
	("INTDIV", " Int\185 ");
	("RMDR", " Rmdr ");
	("FA", "Fa");
  ("SMALLNONE", "n1");
  ("SMALLNTWO", "n2");
  ("XBARONE", "\1941");
  ("XBARTWO", "\1942");
  ("SXONE", "sx1");
  ("SXTWO", "sx2");
  ("SP", "sp");
  ("PHAT", "\127\199");
  ("PHATONE", "\127\1991");
  ("PHATTWO", "\127\1992");
  ("LEFT", "Left");
  ("RIGHT", "Right");
  ("POVERY", "P/Y");
  ("COVERY", "C/Y");
  ("FB", "Fb");
  ("LETTERF", "F");
  ("SMALLZ", "z");
  ("SMALLP", "p");
  ("SMALLT", "t");
  ("SE", "se");
  ("XSQUARE", "\230\086\229\194");
  ("RSQUARE", "r\229\194");
  ("ADF", "Adf");
  ("EDF", "Edf");
  ("DF", "df");
  ("SSA", "SSa");
  ("MSA", "MSa");
  ("SSE", "SSe");
  ("MSE", "MSe");
  ("FAB", "Fab");
  ("BDF", "Bdf");
  ("ABDF", "ABdf");
  ("PA", "pa");
  ("PB", "pb");
  ("PAB", "pab");
  ("CELLSUM", "CellSum(");
  ("CELLPROD", "CellProd(");
  ("CELLMIN", "CellMin(");
  ("CELLMAX", "CellMax(");
  ("CELLMEAN", "CellMean(");
  ("CELLMEDIAN", "CellMedian(");
  ("CELLIF", "CellIf(");
  ("YGRAPH", "\127\240");
  ("RGRAPH", "\127\241");
  ("XT", "\127\244t");
  ("YT", "\127\240t");
  ("XGRAPH", "\127\244");
  ("SSB", "SSb");
  ("SSAB", "SSab");
  ("MSB", "MSb");
  ("MSAB", "MSab");
  ("UNITNS", "[ns]");
  ("UNITMICROS", "[\230\075s]");
  ("UNITMS", "[ms]");
  ("UNITS", "[s]");
  ("UNITMIN", "[min]");
  ("UNITH", "[h]");
  ("UNITDAY", "[day]");
  ("UNITWEEK", "[week]");
  ("UNITYEAR", "[yr]");
  ("UNITSYR", "[s-yr]");
  ("UNITTYR", "[t-yr]");
  ("UNITCELSIUS", "[\140C]");
  ("UNITK", "[K]");
  ("UNITFAHRENHEIT", "[\140F]");
  ("UNITRANKINE", "[\140R]");
  ("UNITU", "[u]");
  ("UNITG", "[g]");
  ("UNITKG", "[kg]");
  ("UNITLB", "[lb]");
  ("UNITOZ", "[oz]");
  ("UNITSLUG", "[slug]");
  ("UNITTONSHORT", "[ton(short)]");
  ("UNITTONLONG", "[ton(long)]");
  ("UNITMTON", "[mton]");
  ("UNITLATM", "[l-atm]");
  ("UNITFTLBF", "[ft\230\170lbf]");
  ("UNITCALIT", "[cal\231\073\231\084]");
  ("UNITCALTH", "[cal\231\116\231\104]");
  ("UNITBTU", "[Btu]");
  ("UNITKWH", "[kW\230\170h]");
  ("UNITKGFM", "[kgf\230\170m]");
  ("UNITPA", "[Pa]");
  ("UNITKPA", "[kPa]");
  ("UNITBAR", "[bar]");
  ("UNITMMHTWOO", "[mmH\229\210O]");
  ("UNITMMHG", "[mmHg]");
  ("UNITINHTWOO", "[inH\229\210O]");
  ("UNITINHG", "[inHg]");
  ("UNITLBFPINSQUARE", "[lbf/in\229\194]");
  ("UNITKGFPCMSQUARE", "[kgf/cm\229\194]");
  ("UNITATM", "[atm]");
  ("UNITDYNE", "[dyne]");
  ("UNITN", "[N]");
  ("UNITKGF", "[kgf]");
  ("UNITLBF", "[lbf]");
  ("UNITTONF", "[tonf]");
  ("UNITFM", "[fm]");
  ("UNITMM", "[mm]");
  ("UNITCM", "[cm]");
  ("UNITM", "[m]");
  ("UNITMIL", "[Mil]");
  ("UNITIN", "[in]");
  ("UNITFT", "[ft]");
  ("UNITYD", "[yd]");
  ("UNITFATH", "[fath]");
  ("UNITRD", "[rd]");
  ("UNITMILE", "[mile]");
  ("UNITNMILE", "[n mile]");
  ("UNITACRE", "[acre]");
  ("UNITHA", "[ha]");
  ("UNITCMSQUARE", "[cm\229\194]");
  ("UNITMSQUARE", "[m\229\194]");
  ("UNITKMSQUARE", "[km\229\194]");
  ("UNITINSQUARE", "[in\229\194]");
  ("UNITFTSQUARE", "[ft\229\194]");
  ("UNITYDSQUARE", "[yd\229\194]");
  ("UNITMILESQUARE", "[mile\229\194]");
  ("UNITMPS", "[m/s]");
  ("UNITKMPH", "[km/h]");
  ("UNITFTPS", "[ft/s]");
  ("UNITMPH", "[mile/h]");
  ("UNITKNOT", "[knot]");
  ("UNITML", "[mL]");
  ("UNITL", "[L]");
  ("UNITTSP", "[tsp]");
  ("UNITCMCUBE", "[cm\229\195]");
  ("UNITMCUBE", "[m\229\195]");
  ("UNITTBSP", "[tbsp]");
  ("UNITINCUBE", "[in\229\195]");
  ("UNITFTCUBE", "[ft\229\195]");
  ("UNITFLOZUK", "[fl_oz(UK)]");
  ("UNITFLOZUS", "[fl_oz(US)]");
  ("UNITCUP", "[cup]");
  ("UNITPT", "[pt]");
  ("UNITQT", "[qt]");
  ("UNITGALUS", "[gal(US)]");
  ("UNITGALUK", "[gal(UK)]");
  ("UNITMICROM", "[\230\075m]");
  ("UNITMG", "[mg]");
  ("UNITANGSTROM", "[\229\006]");
  ("UNITAU", "[AU]");
  ("UNITLY", "[l.y.]");
  ("UNITPC", "[pc]");
  ("UNITFTLBFPS", "[ft\230\170lbf/s]");
  ("UNITCALTHPS", "[cal\231\116\231\104/s]");
  ("UNITHP", "[hp]");
  ("UNITBTUPM", "[Btu/min]");
  ("UNITW", "[W]");
  ("UNITEV", "[eV]");
  ("UNITERG", "[erg]");
  ("UNITJ", "[J]");
  ("UNITCALFIFTEEN", "[cal\229\209\229\213]");
  ("UNITKCALFIFTEEN", "[kcal\229\209\229\213]");
  ("UNITKCALTH", "[kcal\231\116\231\104]");
  ("UNITKCALIT", "[kcal\231\073\231\084]");
	("IF", "If ");
	("THEN", "Then ");
	("ELSE", "Else ");
	("IFEND", "IfEnd");
	("FOR", "For ");
	("TO", " To ");
	("STEP", " Step ");
	("NEXT", "Next");
	("WHILE", "While ");
	("WHILEEND", "WhileEnd");
	("DO", "Do");
	("LPWHILE", "LpWhile ");
	("RETURN", "Return");
	("BREAK", "Break");
	("STOP", "Stop");
	("LOCATE", "Locate ");
	("SEND", "Send(");
  ("RECEIVE", "Receive(");
  ("OPENCOMPORTTHIRTYEIGHTK", "OpenComport38k");
  ("CLOSECOMPORTTHIRTYEIGHTK", "CloseComport38k");
  ("SENDTHIRTYEIGHTK", "Send38k ");
  ("RECEIVETHIRTYEIGHTK", "Receive38k ");
	("CLRTEXT", "ClrText");
	("CLRGRAPH", "ClrGraph");
	("CLRLIST", "ClrList ");
	("LINEARREGAPLUSBX", "LinearReg(a+bx) ");
	("SLNORMAL", "S-L-Normal");
	("SLTHICK", "S-L-Thick");
	("SLBROKEN", "S-L-Broken");
	("SLDOT", "S-L-Dot");
	("DRAWGRAPH", "DrawGraph");
	("PLOTPHASE", "PlotPhase ");
	("DRAWDYNA", "DrawDyna");
	("DRAWSTAT", "DrawStat");
	("DRAWFTGCON", "DrawFTG-Con");
  ("DRAWFTGPLT", "DrawFTG-Plt");
  ("DRAWRCON", "DrawR-Con");
  ("DRAWRPLT", "DrawR-Plt");
  ("DRAWRSIGMACON", "DrawR\230\081-Con");
  ("DRAWRSIGMAPLT", "DrawR\230\081-Plt");
  ("DRAWWEB", "DrawWeb ");
	("NORMALG", "NormalG ");
	("THICKG", "ThickG ");
	("BROKENTHICKG", "BrokenThickG ");
	("DISPFTBL", "DispF-Tbl");
  ("DISPRTBL", "DispR-Tbl");
  ("SIMPLIFYAUTO", "SimplifyAuto");
  ("SIMPLIFYMAN", "SimplifyMan");
  ("NPPLOT", "NPPlot");
  ("SINUSOIDAL", "Sinusoidal");
  ("SINREG", "SinReg ");
  ("LOGISTIC", "Logistic");
  ("LOGISTICREG", "LogisticReg ");
  ("PIE", "Pie");
	("BAR", "Bar");
	("DOTG", "DotG ");
	("ONEVARIABLE", "1-Variable ");
  ("TWOVARIABLE", "2-Variable ");
  ("LINEARREGAXPLUSB", "LinearReg(ax+b) ");
  ("MEDMEDLINE", "Med-MedLine ");
  ("QUADREG", "QuadReg ");
  ("CUBICREG", "CubicReg ");
  ("QUARTREG", "QuartReg ");
  ("LOGREG", "LogReg ");
  ("EXPREGAEPOWBX", "ExpReg(a\230\170e^bx) ");
  ("POWERREG", "PowerReg ");
	("SGPH1", "S-Gph1 ");
	("SGPH2", "S-Gph2 ");
	("SGPH3", "S-Gph3 ");
	("SQUARE", "Square");
	("CROSS", "Cross");
	("DOT", "Dot");
	("SCATTER", "Scatter");
	("XYLINE", "xyLine");
	("HIST", "Hist");
	("MEDBOX", "MedBox");
	("NDIST", "N-Dist");
	("BROKEN", "Broken");
	("LINEAR", "Linear");
  ("MEDMED", "Med-Med");
  ("QUAD", "Quad");
  ("CUBIC", "Cubic");
  ("QUART", "Quart");
  ("LLOG", "Log");
  ("EXPAEPOWBX", "Exp(a\230\170e^bx)");
  ("POWERKEYWORD", "Power");
  ("EXPREGABPOWX", "ExpReg(a\230\170b^x) ");
	("SWINDAUTO", "S-WindAuto");
	("SWINDMAN", "S-WindMan");
	("GRAPHXEQ", "Graph X=");
	("YEQUALTYPE", "Y=Type");
	("REQUALTYPE", "r=Type");
	("PARAMTYPE", "ParamType");
	("XEQUALTYPE", "X=Type");
	("XGTYPE", "X>Type");
	("XLTYPE", "X<Type");
	("YGTYPE", "Y>Type");
	("YLTYPE", "Y<Type");
	("YGEQTYPE", "Y\018Type");
	("YLEQTYPE", "Y\016Type");
	("XGEQTYPE", "X\018Type");
	("XLEQTYPE", "X\016Type");
	("GCONNECT", "G-Connect");
	("GPLOT", "G-Plot");
	("RESIDNONE", "Resid-None");
  ("RESIDLIST", "Resid-List ");
	("BGNONE", "BG-None");
	("BGPICT", "BG-Pict ");
	("GRIDOFF", "GridOff");
	("GRIDON", "GridOn");
	("EXPABPOWX", "Exp(a\230\170b^x)");
	("DVAR", "D Var ");
	("QONEQTHREETYPESTD", "Q1Q3TypeStd");
  ("VARRANGE", "VarRange");
  ("QONEQTHREETYPEONDATA", "Q1Q3TypeOnData");
	("SKETCHNORMAL", "SketchNormal ");
	("SKETCHTHICK", "SketchThick ");
	("SKETCHBROKEN", "SketchBroken ");
	("SKETCHDOT", "SketchDot ");
	("ANTYPE", "a\229\222Type");
  ("ANPLUSONETYPE", "a\229\222\229\219\229\206Type");
  ("ANPLUSTWOTYPE", "a\229\222\229\219\229\207Type");
	("STOPICT", "StoPict ");
	("RCLPICT", "RclPict ");
	("STOGMEM", "StoGMEM ");
	("RCLGMEM", "RclGMEM ");
	("STOVWIN", "StoV-Win ");
	("RCLVWIN", "RclV-Win ");
	("PERCENTSIGN", "\037");
	("DATA", "Data");
	("MENU", "Menu ");
	("RCLCAPT", "RclCapt ");
	("TANGENT", "Tangent ");
	("NORMAL", "Normal ");
	("INVERSE", "Inverse ");
	("VERTICAL", "Vertical ");
	("HORIZONTAL", "Horizontal ");
	("TEXT", "Text ");
	("CIRCLE", "Circle");
	("FLINE", "F-Line ");
	("PLOTON", "PlotOn ");
	("PLOTOFF", "PlotOff ");
	("PLOTCHG", "PlotChg ");
	("PXLON", "PxlOn ");
	("PXLOFF", "PxlOff ");
	("PXLCHG", "PxlChg ");
	("PXLTEST", "PxlTest(");
	("SORTA", "SortA(");
	("SORTD", "SortD(");
	("VARLISTONE", "VarList1");
  ("VARLISTTWO", "VarList2");
  ("VARLISTTHREE", "VarList3");
  ("VARLISTFOUR", "VarList4");
  ("VARLISTFIVE", "VarList5");
  ("VARLISTSIX", "VarList6");
  ("FILEONE", "File1");
  ("FILETWO", "File2");
  ("FILETHREE", "File3");
  ("FILEFOUR", "File4");
  ("FILEFIVE", "File5");
  ("FILESIX", "File6");
	("YDRAWSPEEDNORM", "Y=DrawSpeedNorm");
	("YDRAWSPEEDHIGH", "Y=DrawSpeedHigh");
	("FUNCON", "FuncOn");
	("SIMULON", "SimulOn");
	("AXESON", "AxesOn");
	("COORDON", "CoordOn");
	("LABELON", "LabelOn");
	("DERIVON", "DerivOn");
	("LOCUSON", "LocusOn");
	("SIGMADISPON", "\230\081dispOn");
	("GSELON", "G SelOn ");
	("TSELON", "T SelOn ");
	("DSELON", "D SelOn ");
	("DRAWON", "DrawOn");
	("ABOVERC", "ab/c");
	("DOVERC", "d/c");
	("FUNCOFF", "FuncOff");
	("SIMULOFF", "SimulOff");
	("AXESOFF", "AxesOff");
	("COORDOFF", "CoordOff");
	("LABELOFF", "LabelOff");
	("DERIVOFF", "DerivOff");
	("LOCUSOFF", "LocusOff");
	("SIGMADISPOFF", "\230\081dispOff");
	("GSELOFF", "G SelOff ");
	("TSELOFF", "T SelOff ");
	("DSELOFF", "D SelOff ");
	("DRAWOFF", "DrawOff");
	("TODMS", "\230\158DMS");
	("TOAPLUSBI", "\230\158a+b\127\080");
	("TORTHETA", "\230\158r\127\084\206");
	("REAL", "Real");
	("APLUSBI", "a+b\127\080");
	("RTHETA", "r\127\084\206");
	("ENGON", "EngOn");
	("ENGOFF", "EngOff");
	("SELAZERO", "Sel a\229\205");
  ("SELAONE", "Sel a\229\206");
	("CN", "c\229\222");
  ("CNPLUSONE", "c\229\222\229\219\229\206");
  ("CNPLUSTWO", "c\229\222\229\219\229\207");
  ("CZERO", "c\229\205");
  ("CONE", "c\229\206");
  ("CTWO", "c\229\207");
  ("CNSTART", "c\229\222Start");
  ("INEQTYPEAND", "IneqTypeAnd");
	("FN", "f\229\222");
	("FILE", "File ");
	("VARLIST", "VarList ");
	("CLRMAT", "ClrMat ");
	("ZOOMAUTO", "ZoomAuto");
	("XDOT", "Xdot");
	("RIGHTXDOT", "RightXdot");
  ("DRAWDISTNORM", "DrawDistNorm ");
  ("DRAWDISTT", "DrawDistT ");
  ("DRAWDISTCHI", "DrawDistChi ");
  ("DRAWDISTF", "DrawDistF ");
	("NONE", "None");
	("STICKLENGTH", "StickLength");
	("STICKHORIZ", "StickHoriz");
	("INEQTYPEOR", "IneqTypeOr");
	("GRAPHXG", "Graph X>");
	("GRAPHXL", "Graph X<");
	("GRAPHXGEQ", "Graph X\018");
	("GRAPHXLEQ", "Graph X\016");
	("STRJOIN", "StrJoin(");
	("STRLEN", "StrLen(");
	("STRCMP", "StrCmp(");
	("STRSRC", "StrSrc(");
	("STRLEFT", "StrLeft(");
	("STRRIGHT", "StrRight(");
	("STRMID", "StrMid(");
	("EXPSTR", "Exp\230\158Str(");
	("EXPPAR", "Exp(");
	("STRUPR", "StrUpr(");
	("STRLWR", "StrLwr(");
	("STRINV", "StrInv(");
	("STRSHIFT", "StrShift(");
	("STRROTATE", "StrRotate(");
	("STR", "Str ");
	("NORMPD", "NormPD(");
  ("NORMCD", "NormCD(");
  ("INVNORMCD", "InvNormCD(");
  ("TPD", "tPD(");
  ("TCD", "tCD(");
  ("INVTCD", "InvTCD(");
  ("CHIPD", "ChiPD(");
  ("CHICD", "ChiCD(");
  ("INVCHICD", "InvChiCD(");
  ("FPD", "FPD(");
  ("FCD", "FCD(");
  ("INVFCD", "InvFCD(");
  ("BINOMIALPD", "BinomialPD(");
  ("BINOMIALCD", "BinomialCD(");
  ("INVBINOMIALCD", "InvBinomialCD(");
  ("POISSONPD", "PoissonPD(");
  ("POISSONCD", "PoissonCD(");
  ("INVPOISSONCD", "InvPoissonCD(");
  ("GEOPD", "GeoPD(");
  ("GEOCD", "GeoCD(");
  ("INVGEOCD", "InvGeoCD(");
  ("HYPERGEOPD", "HypergeoPD(");
  ("HYPERGEOCD", "HypergeoCD(");
  ("INVHYPERGEOCD", "InvHypergeoCD(");
  ("SMPLSI", "Smpl_SI(");
  ("SMPLSFV", "Smpl_SFV(");
  ("CMPDN", "Cmpd_n(");
  ("CMPDIPERCENT", "Cmpd_I\037(");
  ("CMPDPV", "Cmpd_PV(");
  ("CMPDPMT", "Cmpd_PMT(");
  ("CMPDFV", "Cmpd_FV(");
  ("CASHNPV", "Cash_NPV(");
  ("CASHIRR", "Cash_IRR(");
  ("CASHPBP", "Cash_PBP(");
  ("CASHNFV", "Cash_NFV(");
  ("AMTBAL", "Amt_BAL(");
  ("AMTINT", "Amt_INT(");
  ("AMTPRN", "Amt_PRN(");
  ("AMTSINT", "Amt_\230\081INT(");
  ("AMTSPRN", "Amt_\230\081PRN(");
  ("CNVTEFF", "Cnvt_EFF(");
  ("CNVTAPR", "Cnvt_APR(");
  ("COST", "Cost(");
  ("SELL", "Sell(");
  ("MARGIN", "Margin(");
  ("PMTEND", "PmtEnd");
  ("PMTBGN", "PmtBgn");
  ("BONDPRC", "Bond_PRC(");
  ("BONDYLD", "Bond_YLD(");
  ("DATEMODETHREESIXTYFIVE", "DateMode365");
  ("DATEMODETHREESIXTY", "DateMode360");
  ("PERIODSANNUAL", "PeriodsAnnual");
  ("PERIODSSEMI", "PeriodsSemi");
  ("DAYSPRD", "Days_Prd(");
  ("ONESAMPLEZTEST", "OneSampleZTest ");
  ("TWOSAMPLEZTEST", "TwoSampleZTest ");
  ("ONEPROPZTEST", "OnePropZTest ");
  ("TWOPROPZTEST", "TwoPropZTest ");
  ("ONESAMPLETTEST", "OneSampleTTest ");
  ("TWOSAMPLETTEST", "TwoSampleTTest ");
  ("LINREGTTEST", "LinRegTTest ");
  ("CHIGOFTEST", "ChiGOFTest ");
  ("CHITEST", "ChiTest ");
  ("TWOSAMPLEFTEST", "TwoSampleFTest ");
  ("ONEWAYANOVA", "OneWayANOVA ");
  ("TWOWAYANOVA", "TwoWayANOVA ");
  ("XONEINVN", "x1InvN");
  ("XTWOINVN", "x2InvN");
  ("XINV", "xInv");
  ("ZLOW", "zLow");
  ("ZUP", "zUp");
  ("TLOW", "tLow");
  ("TUP", "tUp")
];;

